### PR TITLE
Sitewhere 1.6.0

### PR DESCRIPTION
**Pull request by cwalker67**
add gradle build

### CODE REVIEW

**Comment by anhdenday** [comment]
It's seem that when I using grade my IDE is load more slowly and also I use maven familiar than gradle, please keep one version for maven!
Thanks

**Comment by derekadams** [comment]
The problem we are running into with the build is that we are having to hack some parts to make Maven do what we want and it's getting hard to manage. Gradle has better handling for separating out individual tasks and properly handling the dependencies. Gradle is also a lot more concise and programmable. Unfortunately, we can't keep up with multiple build systems, so we are looking to move away from Maven completely in 1.6. We understand that this may cause short-term problems for some developers, but it will make the build process much more robust in the long run. Which IDE are you using by the way? We tend to build from the command line and performance is not bad.

**Comment by anhdenday** [comment]
I am using eclipse IDE, anyway, if you change to gradle, please update the tutorial. Thanks

**Comment by derekadams** [comment]
Most of us use Eclipse as well, so we will try to keep performance acceptable. We are planning to add some new documentation with the 1.6 release and it will include the updated build instructions.

**Pull request merged**
